### ISSUE TITLE
Datastore stats collection issue "Failed to retrieve stats for Entity..."

### ISSUE THREAD

**Issue by eric-becker** [SYNAXON/GraphiteReceiver#26]
I have statsfeeder and GraphiteReceiver up and working with HostSystem and VirtualMachine stats.  Everything seems to work with just these two types.  However when I enable datastore stats collection

```
        <childType>HostSystem,VirtualMachine,Datastore</childType>
```

I get the following error for each datastore:

436528 [Thread-3051] WARN  com.vmware.ee.statsfeeder.StatsRetriever  - Failed to retrieve stats for Entity [[vCenter]Datastore_01[Datastore]]
java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:504)
        at java.lang.Integer.parseInt(Integer.java:527)
        at com.vmware.ee.statsfeeder.StatsRetriever.buildDateList(StatsRetriever.java:322)
        at com.vmware.ee.statsfeeder.StatsRetriever.processStats(StatsRetriever.java:284)
        at com.vmware.ee.statsfeeder.StatsRetriever.onComplete(StatsRetriever.java:99)
        at com.vmware.ee.statsfeeder.StatsRetriever.access$300(StatsRetriever.java:24)
        at com.vmware.ee.statsfeeder.StatsRetriever$1.run(StatsRetriever.java:189)

**Comment by jholle** [comment]
I too have a similar issue. Hostsystem and VirtualMachine work great, but adding Datastore doesn't yeild any datastore metrics and fills my log repeatedly with the following entry:

```
2    [Thread-21] FATAL de.synaxon.graphitereceiver.MetricsReceiver  - Unexpected error occurred during metrics collection.
java.lang.NullPointerException
        at de.synaxon.graphitereceiver.MetricsReceiver.receiveStats(MetricsReceiver.java:621)
        at com.vmware.ee.statsfeeder.StatsRetriever.onComplete(StatsRetriever.java:141)
        at com.vmware.ee.statsfeeder.StatsRetriever.access$300(StatsRetriever.java:24)
        at com.vmware.ee.statsfeeder.StatsRetriever$1.run(StatsRetriever.java:189)
```

**Comment by toni-moreno** [comment]
Hi @beanfield33 and @jholle , how do you fixed this error ? is still happening ?

**Comment by eric-becker** [comment]
Unfortunately i don't have a fix out workaround.  It still happens if I enable HostSystem,VirtualMachine,Datastore collection.

**Comment by jholle** [comment]
Me neither. I just stopped including "datastore" as a metrics collection type.

**Comment by vmwiz** [comment]
To get Datastore entity stats you must increase the vCenter statistics collections: Inventory->Administration->Server Settings; then go and edit each Statistics Intervals, set their Statistics Level to at least Level 3
