### ISSUE TITLE
Error on scalePercent()

### ISSUE THREAD

**Issue by toni-moreno** [SYNAXON/GraphiteReceiver#39]
Sometimes GraphiteReceiver shows the following stack trace.

```

016-02-04 17:13:57,274 [Thread-21403] FATAL MetricsReceiver  - Unexpected error occurred during metrics collection.
java.lang.NumberFormatException: empty String
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:992)
        at java.lang.Double.valueOf(Double.java:475)
        at de.synaxon.graphitereceiver.core.MetricsReceiver.scalePercent(MetricsReceiver.java:473)
        at de.synaxon.graphitereceiver.core.MetricsReceiver.sendMetric(MetricsReceiver.java:426)
        at de.synaxon.graphitereceiver.core.MetricsReceiver.sendMetric(MetricsReceiver.java:396)
        at de.synaxon.graphitereceiver.core.MetricsReceiver.receiveStats(MetricsReceiver.java:358)
        at com.vmware.ee.statsfeeder.StatsRetriever.onComplete(StatsRetriever.java:140)
        at com.vmware.ee.statsfeeder.StatsRetriever$1.run(StatsRetriever.java:190)
2016-02-04 17:13:57,277 [Thread-21403] FATAL MetricsReceiver  - Unexpected error occurred during metrics collection.
java.lang.NumberFormatException: empty String
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:992)
        at java.lang.Double.valueOf(Double.java:475)
        at de.synaxon.graphitereceiver.core.MetricsReceiver.scalePercent(MetricsReceiver.java:473)
        at de.synaxon.graphitereceiver.core.MetricsReceiver.sendMetric(MetricsReceiver.java:426)
        at de.synaxon.graphitereceiver.core.MetricsReceiver.sendMetric(MetricsReceiver.java:396)
        at de.synaxon.graphitereceiver.core.MetricsReceiver.receiveStats(MetricsReceiver.java:358)
        at com.vmware.ee.statsfeeder.StatsRetriever.onComplete(StatsRetriever.java:140)
        at com.vmware.ee.statsfeeder.StatsRetriever$1.run(StatsRetriever.java:190)
2016-02-04 17:13:57,278 [Thread-21403] FATAL MetricsReceiver  - Unexpected error occurred during metrics collection.
java.lang.NumberFormatException: empty String
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:992)
        at java.lang.Double.valueOf(Double.java:475)
        at de.synaxon.graphitereceiver.core.MetricsReceiver.scalePercent(MetricsReceiver.java:473)
        at de.synaxon.graphitereceiver.core.MetricsReceiver.sendMetric(MetricsReceiver.java:426)
        at de.synaxon.graphitereceiver.core.MetricsReceiver.sendMetric(MetricsReceiver.java:396)
        at de.synaxon.graphitereceiver.core.MetricsReceiver.receiveStats(MetricsReceiver.java:358)
        at com.vmware.ee.statsfeeder.StatsRetriever.onComplete(StatsRetriever.java:140)
        at com.vmware.ee.statsfeeder.StatsRetriever$1.run(StatsRetriever.java:190)
2016-02-04 17:13:57,283 [Timer-0] INFO  MetricsReceiver  - onEndRetrieval PerformanceMetricsCountForEachRun: 1941726

```

**Comment by toni-moreno** [comment]
Hi @kofrezo this issue can be closed when   this PR https://github.com/SYNAXON/GraphiteReceiver/pull/41 will be merged. Lots of thanks @cosm0s
