### ISSUE TITLE
[BugDetected & workarround] on new use_alternate_vm_prefix_sufix parameter

### ISSUE THREAD

**Issue by toni-moreno** [SYNAXON/GraphiteReceiver#40]
Since last merges we have added a new "use_alternate_vm_prefix_sufix" set to true by default

But this stack trace is shown when statsfeeder is executed.

```
60707 [Thread-40] FATAL de.synaxon.graphitereceiver.core.MetricsReceiver – Unexpected error occurred during metrics collection.
java.lang.NullPointerException
at de.synaxon.graphitereceiver.utils.Utils.getNode(Utils.java:172)
at de.synaxon.graphitereceiver.core.MetricsReceiver.receiveStats(MetricsReceiver.java:350)
at com.vmware.ee.statsfeeder.StatsRetriever.onComplete(StatsRetriever.java:141)
at com.vmware.ee.statsfeeder.StatsRetriever.access$300(StatsRetriever.java:24)
at com.vmware.ee.statsfeeder.StatsRetriever$1.run(StatsRetriever.java:189)
60711 [Thread-40] FATAL de.synaxon.graphitereceiver.core.MetricsReceiver – Unexpected error occurred during metrics collection.
```

@cosm0s and I we are working in a fix to check whether the file exists and also set by default this parameter to false , in the meanwhile the workaround is set the parameter use_alternate_vm_prefix_sufix to false as suggested  in https://labs.vmware.com/flings/statsfeeder#comment-547346

Thanks you very much

**Comment by toni-moreno** [comment]
Hi @kofrezo this issue can be closed when   this PR https://github.com/SYNAXON/GraphiteReceiver/pull/41 will be merged. Lots of thanks @cosm0s
