### ISSUE TITLE
Unexpected error occurred during metrics collection- java.lang.NullPointerException

### ISSUE THREAD

**Issue by samuellay** [SYNAXON/GraphiteReceiver#45]
I applied the workaround mentioned in an earlier issue report:

```
<property>
  <name>use_alternate_vm_prefix_sufix</name>
  <value>false</value>
</property>
```

I still get:

```
# ./StatsFeeder.sh -h fitw08v110.us.fit -u '**************' -p ************ -c ./config/GRsampleConfig.xml
StatsFeeder [4.1 (Build jenkins-Statsfeeder-697)]
Copyright (c) 2011-2013 VMware, Inc`
All rights reserved
-----------------------------
Managed entity: com.vmware.vim25.ManagedObjectReference@39178c5c
Current supported: true
Refresh rate: 20
Summary supported: true
-----------------------------
-----------------------------
Managed entity: com.vmware.vim25.ManagedObjectReference@382b6004
Current supported: true
Refresh rate: 20
Summary supported: true
-----------------------------
1    [Thread-11] FATAL de.synaxon.graphitereceiver.core.MetricsReceiver  - Unexpected error occurred during metrics collection.
java.lang.NullPointerException
        at de.synaxon.graphitereceiver.core.MetricsReceiver.receiveStats(MetricsReceiver.java:303)
        at com.vmware.ee.statsfeeder.StatsRetriever.onComplete(StatsRetriever.java:141)
        at com.vmware.ee.statsfeeder.StatsRetriever.access$300(StatsRetriever.java:24)
        at com.vmware.ee.statsfeeder.StatsRetriever$1.run(StatsRetriever.java:189)
55   [Thread-4] FATAL de.synaxon.graphitereceiver.core.MetricsReceiver  - Unexpected error occurred during metrics collection.
java.lang.NullPointerException
        at de.synaxon.graphitereceiver.core.MetricsReceiver.receiveStats(MetricsReceiver.java:303)
        at com.vmware.ee.statsfeeder.StatsRetriever.onComplete(StatsRetriever.java:141)
        at com.vmware.ee.statsfeeder.StatsRetriever.access$300(StatsRetriever.java:24)
        at com.vmware.ee.statsfeeder.StatsRetriever$1.run(StatsRetriever.java:189)
101  [Thread-4] FATAL de.synaxon.graphitereceiver.core.MetricsReceiver  - Unexpected error occurred during metrics collection.
java.lang.NullPointerException
        at de.synaxon.graphitereceiver.core.MetricsReceiver.receiveStats(MetricsReceiver.java:303)
        at com.vmware.ee.statsfeeder.StatsRetriever.onComplete(StatsRetriever.java:141)
        at com.vmware.ee.statsfeeder.StatsRetriever.access$300(StatsRetriever.java:24)
        at com.vmware.ee.statsfeeder.StatsRetriever$1.run(StatsRetriever.java:189)
...

```

[GRsampleConfig.zip](https://github.com/SYNAXON/GraphiteReceiver/files/194002/GRsampleConfig.zip)

**Comment by samuellay** [comment]
Sorry about the formatting; I pasted from my console window w/o thinking about mark-up . . .

**Comment by narioinc** [comment]
Following the suggestion to resolve this issue, i too ended up with the logs similar to the one posted by samuellay. 
The line here is the issue:
String instanceName = (this.rules.get("instanceName") != null)? RuleUtils.applyRules(metricSet.getInstanceId(),this.rules.get("instanceName")):metricSet.getInstanceId();

is metricSet probably coming up as null ?

**Comment by poetimp** [comment]
Using the comment from  @narioinc as a spring board, in config/GRsampleConfig.xml

I set 

```
<property>
   <name>names_transformation_rules</name>
   <value>true</value>
</property>
<property>
   <name>names_transformation_rules_path</name>
   <value>config/rules.xml</value>
</property>
```

Then I created a rules.xml in the config directory based on: [https://github.com/SYNAXON/GraphiteReceiver/issues/37](url)

And the errors went away and I am getting data.
