### ISSUE TITLE
BUG: on getting data from Entity "ResourcePool"

### ISSUE THREAD

**Issue by toni-moreno** [SYNAXON/GraphiteReceiver#6]
```
2677 [Thread-3] WARN  com.vmware.ee.statsfeeder.StatsRetriever  - Failed to retrieve stats for Entity [[vCenter]MYRESROUCE_POOL[ResourcePool]]
javax.xml.ws.soap.SOAPFaultException: A specified parameter was not correct.
metricId
        at com.sun.xml.internal.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:178)
        at com.sun.xml.internal.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:119)
        at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:108)
        at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:78)
        at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:107)
        at $Proxy35.queryPerf(Unknown Source)
        at com.vmware.ee.statsfeeder.AbstractStatsFeeder.getPerfStats(AbstractStatsFeeder.java:148)
        at com.vmware.ee.statsfeeder.StatsRetriever$1.run(StatsRetriever.java:186)
```

**Comment by toni-moreno** [comment]
```
13242 [Thread-33] WARN  com.vmware.ee.statsfeeder.StatsRetriever  - Failed to retrieve stats for Entity [[vCenter]DATASTORE_TEST_01[Datastore]]
java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
        at java.lang.Integer.parseInt(Integer.java:470)
        at java.lang.Integer.parseInt(Integer.java:499)
        at com.vmware.ee.statsfeeder.StatsRetriever.buildDateList(StatsRetriever.java:322)
        at com.vmware.ee.statsfeeder.StatsRetriever.processStats(StatsRetriever.java:284)
        at com.vmware.ee.statsfeeder.StatsRetriever.onComplete(StatsRetriever.java:99)
        at com.vmware.ee.statsfeeder.StatsRetriever.access$300(StatsRetriever.java:24)
        at com.vmware.ee.statsfeeder.StatsRetriever$1.run(StatsRetriever.java:189)
```

**Comment by kofrezo** [comment]
Hi Toni,
I'll have a look at your submitted issues this week. Thanks for your patience.

**Comment by toni-moreno** [comment]
Hi @kofrezo , I had an error in the config.xml , after reconfiguring

I'm configuring this 

```
        <entities>
            <receivers>graphite</receivers>
            <container>
                <name>vCenter</name>
                <type>Folder</type>
            </container>
            <childType>ResourcePool</childType>
            <exceptions></exceptions>
            <intervalId>300</intervalId>
            <maxSamples>45</maxSamples>
            <statsList>
                <!--stats specific to Resource Pools -->
                <stat>cpu.capacity.contention.average</stat>
                <stat>cpu.capacity.demand.average</stat>
                <stat>cpu.capacity.entitlement.average</stat>
                <stat>cpu.capacity.provisioned.average</stat>
                <stat>cpu.capacity.usage.average</stat>
            </statsList>
        </entities>
```

After that this error happens

```
1220 [Thread-3] WARN  com.vmware.ee.statsfeeder.StatsRetriever  - Failed to retrieve stats for Entity [[vCenter]RP_TEST_1[ResourcePool]]
javax.xml.ws.soap.SOAPFaultException: A specified parameter was not correct.
metricId
        at com.sun.xml.internal.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:178)
        at com.sun.xml.internal.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:119)
        at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:108)
        at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:78)
        at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:107)
        at $Proxy35.queryPerf(Unknown Source)
        at com.vmware.ee.statsfeeder.AbstractStatsFeeder.getPerfStats(AbstractStatsFeeder.java:148)
        at com.vmware.ee.statsfeeder.StatsRetriever$1.run(StatsRetriever.java:186)
1223 [Thread-5] WARN  com.vmware.ee.statsfeeder.StatsRetriever  - Failed to retrieve stats for Entity [[vCenter]RP_TEST_2[ResourcePool]]
javax.xml.ws.soap.SOAPFaultException: A specified parameter was not correct.
metricId
        at com.sun.xml.internal.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:178)
        at com.sun.xml.internal.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:119)
        at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:108)
        at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:78)
        at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:107)
        at $Proxy35.queryPerf(Unknown Source)
        at com.vmware.ee.statsfeeder.AbstractStatsFeeder.getPerfStats(AbstractStatsFeeder.java:148)
        at com.vmware.ee.statsfeeder.StatsRetriever$1.run(StatsRetriever.java:186)
1223 [pool-1-thread-1] DEBUG com.vmware.ee.statsfeeder.StatsRetriever  - Retriever ended, status = ERROR
1226 [pool-1-thread-3] DEBUG com.vmware.ee.statsfeeder.StatsRetriever  - Retriever ended, status = ERROR
1220 [Thread-4] WARN  com.vmware.ee.statsfeeder.StatsRetriever  - Failed to retrieve stats for Entity [[vCenter]Resources[ResourcePool]]
javax.xml.ws.soap.SOAPFaultException: A specified parameter was not correct.
metricId
        at com.sun.xml.internal.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:178)
        at com.sun.xml.internal.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:119)
        at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:108)
        at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:78)
        at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:107)
        at $Proxy35.queryPerf(Unknown Source)
        at com.vmware.ee.statsfeeder.AbstractStatsFeeder.getPerfStats(AbstractStatsFeeder.java:148)
        at com.vmware.ee.statsfeeder.StatsRetriever$1.run(StatsRetriever.java:186)
1258 [pool-1-thread-2] DEBUG com.vmware.ee.statsfeeder.StatsRetriever  - Retriever ended, status = ERROR
1261 [Timer-0] DEBUG com.vmware.ee.statsfeeder.VsphereStatsFeeder  - ========== There are [0] retrievers still running at end of collection
1261 [Timer-0] WARN  com.vmware.ee.statsfeeder.VsphereStatsFeeder  - Retrieval completed with errors, check log for details
1261 [Timer-0] DEBUG com.vmware.ee.statsfeeder.VsphereStatsFeeder  - ========== Retrieval Total time: 456
^[[A58623 [Main Thread] DEBUG com.vmware.ee.statsfeeder.Main  - -------------------------------------------------------------
58631 [Main Thread] DEBUG com.vmware.ee.statsfeeder.Main  - Total time: 58596
StatsFeeder exited rc = 1, check log for details
```

**Comment by toni-moreno** [comment]
Hi @kofrezo about Datastores I should say that error was in the metric configurations. Now I'm reconfigured with this:

```
        <entities>
            <receivers>graphite</receivers>
            <container>
                <name>vCenter</name>
                <type>Folder</type>
            </container>
            <childType>Datastore</childType>
            <exceptions></exceptions>
            <intervalId>20</intervalId>

            <maxSamples>1</maxSamples>
            <statsList>
                <!--stats specifig to Datastore -->

                <stat>datastore.throughput.contention.average</stat>
                <stat>datastore.throughput.usage.average</stat>
                <stat>disk.capacity.contention.average</stat>
                <stat>disk.capacity.provisioned.average</stat>
                <stat>disk.capacity.usage.average</stat>

            </statsList>
        </entities>
```

And the metric colected are:

```
esxtest.SC_DATASTORE_TEST_01[Datastore].disk.capacity.contention.average_percent 0 1426507200
esxtest.SC_DATASTORE_TEST_01[Datastore].disk.capacity.contention.average_percent 0 1426509000
esxtest.SC_DATASTORE_TEST_01[Datastore].disk.capacity.contention.average_percent 0 1426510800
esxtest.SC_DATASTORE_TEST_01[Datastore].disk.capacity.usage.average_kiloBytes 1009664 1426435200
esxtest.SC_DATASTORE_TEST_01[Datastore].disk.capacity.usage.average_kiloBytes 1009664 1426437000
esxtest.SC_DATASTORE_TEST_01[Datastore].disk.capacity.usage.average_kiloBytes 1009664 1426438800
```

It has the same "instance leak" bug (https://github.com/SYNAXON/GraphiteReceiver/issues/5) and "[DataStore]" should be removed.

I will try to build a PR with this two corrections..

**Comment by kofrezo** [comment]
When this is the same as #5 I can close this issue too ?

**Comment by toni-moreno** [comment]
Indeed I've corrected the second stacktrace ( error on datastore)  with a correct configuration and adding in my PR , but not the first (error on ResourcePool).... but that is not my first priority...

**Comment by kofrezo** [comment]
Okay. I'll keep this issue open.

**Comment by aleex42** [comment]
Any news here?

Still getting the following error:

```
Failed to retrieve stats for Entity [[vCenter]...[VirtualMachine]]
```
